# Generated by Django 2.1.5 on 2019-12-30 07:39

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='公開時間')),
                ('pub_type', models.IntegerField(choices=[(2, '非公開'), (1, '公開')], verbose_name='記事種別')),
                ('edit_body', ckeditor.fields.RichTextField()),
                ('body', models.TextField(blank=True)),
                ('index', models.TextField(blank=True)),
                ('meta', models.CharField(blank=True, max_length=150, verbose_name='メタ情報')),
                ('sns_intro', models.CharField(blank=True, max_length=140, verbose_name='SNS文章')),
                ('celery_id', models.CharField(blank=True, max_length=36, null=True)),
                ('is_need_celery_change', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('reply_to', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Comment')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='タグ名')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, on_delete='DO_NOTHING', to='article.Category', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='article.Tag', verbose_name='タグ'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete='CASCADE', related_name='thumbnail_article', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
