# Generated by Django 2.1.5 on 2020-01-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_pv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail',
        ),
    ]
