# Generated by Django 2.1.5 on 2020-01-23 13:09

from django.conf import settings
from django.db import migrations
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('article', '0004_remove_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete='CASCADE', related_name='thumbnail_article', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
