# Generated by Django 2.1.5 on 2020-03-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Tag', verbose_name='親タグ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pv',
            field=models.PositiveIntegerField(default=0, verbose_name='PV数'),
        ),
    ]
