# Generated by Django 2.1.5 on 2020-03-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200321_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_pk',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
