# Generated by Django 2.1.5 on 2020-03-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200321_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent_pk',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Tag', verbose_name='親タグ'),
        ),
    ]
