# Generated by Django 2.1.5 on 2020-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20200327_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_post',
            field=models.ManyToManyField(blank=True, related_name='_article_related_post_+', to='article.Article', verbose_name='関連記事'),
        ),
    ]
