# Generated by Django 2.1.5 on 2020-03-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20200327_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_post',
        ),
    ]
