# Generated by Django 2.1.5 on 2020-03-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_remove_article_related_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_article_related_posts_+', to='article.Article', verbose_name='タグ'),
        ),
    ]
