# Generated by Django 2.2.10 on 2020-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_remove_article_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_article_related_posts_+', to='article.Article'),
        ),
    ]
