# Generated by Django 2.2.13 on 2020-07-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_remove_article_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_article_related_posts_+', to='article.Article', verbose_name='関連記事'),
        ),
    ]
