# Generated by Django 2.2.13 on 2020-07-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20200703_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_posts',
        ),
    ]
